version: 0.0
os: linux
files:
  - source: /app/index.html
    destination: /var/www/html/
    overwrite: yes
hooks:
  # The BeforeInstall hook is now empty because we don't have any pre-install tasks.
  # The CodeDeploy agent should be installed via User Data or baked into the AMI.
  AfterInstall:
    - location: app/scripts/start_server.sh
      timeout: 300
      runas: root