# app/appspec.yml

version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root